package school.faang.models;

public enum Category {
    ELECTRONICS,
    CLOTHING_AND_ACCESSORIES,
    BEAUTY_AND_PERSONAL_CARE,
    HOME_AND_FURNITURE,
    SPORTS_AND_OUTDOORS,
    TOYS_AND_GAMES,
    FOOD_AND_BEVERAGES,
    BOOKS_MOVIES_AND_MUSIC,
    AUTOMOTIVE,
    OFFICE_SUPPLIES_AND_STATIONERY,
    PET_SUPPLIES,
    HEALTH_AND_MEDICAL;
}
