server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/werewolf
    username: kraiu
    password: dbsys91
    driverClassName: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
        ddl-auto: update
    properties:
        hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect
            format_sql: true
            default_schema: public

BASE_PACKAGE: ru.kraiush.*

logging:
  level:
    root: ERROR
    org.springframework.web: ERROR
    org.hibernate: ERROR