name: Java CI

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: 17

      - name: Build and test with Gradle
        run: .\gradlew build testClasses -x test -x check -x checkstyleMain -x checkstyleTest --no-daemon
