name: Java CI

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: 17

      - name: Compile and run tests
        run: |
          javac -d out src/**/*.java
          java -cp out com.example.Main